AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a read-only IAM role for AWS Organizations with trust policy to ClouSec main account role.

Parameters:
  ClouSecMainAccountID:
    Type: String
    Description: Enter the ClouSec Main Account ID

  ClouSecMainAccountRoleName:
    Type: String
    Default: clousec-ecs-hub-role
    Description: Enter the ClouSec Main Role Name

  Rolename:
    Type: String
    Default: clousec-organization-readonly-role
    Description: Enter the Organization Role Name

Resources:
  OrganizationReadOnlyRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Ref Rolename
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: 
                Fn::Sub: "arn:aws:iam::${ClouSecMainAccountID}:role/${ClouSecMainAccountRoleName}"
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSOrganizationsReadOnlyAccess"

  CostExplorerPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: CostExplorerPolicy
      Roles:
        - !Ref OrganizationReadOnlyRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - ce:GetCostAndUsage
              - ce:GetReservationPurchaseRecommendation
              - ce:GetPreferences
              - ce:ListSavingsPlansPurchaseRecommendationGeneration
              - ce:ListTagsForResource
              - ce:GetReservationUtilization
              - ce:GetCostCategories
              - ce:GetSavingsPlansPurchaseRecommendation
              - ce:GetSavingsPlansUtilizationDetails
              - ce:GetDimensionValues
              - ce:GetAnomalySubscriptions
              - ce:DescribeReport
              - ce:GetReservationCoverage
              - ce:GetAnomalyMonitors
              - ce:GetUsageForecast
              - ce:DescribeNotificationSubscription
              - ce:DescribeCostCategoryDefinition
              - ce:GetRightsizingRecommendation
              - ce:GetSavingsPlansUtilization
              - ce:GetAnomalies
              - ce:ListCostCategoryDefinitions
              - ce:GetCostForecast
              - ce:GetCostAndUsageWithResources
              - ce:ListCostAllocationTags
              - ce:GetSavingsPlanPurchaseRecommendationDetails
              - ce:GetSavingsPlansCoverage
              - ce:GetConsoleActionSetEnforced
              - ce:GetTags
            Resource: "*"

Outputs:
  OrganizationReadOnlyRoleArn:
    Description: ARN of the Organization ReadOnly Role
    Value: !GetAtt OrganizationReadOnlyRole.Arn
