AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Security Logging Solution with WAF and CloudTrail'

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name
    AllowedValues:
      - dev
      - test
      - prod

  LogRetentionDays:
    Type: Number
    Default: 90
    Description: Number of days to retain logs before transitioning to STANDARD_IA

  ArchiveRetentionDays:
    Type: Number
    Default: 180
    Description: Number of days to retain logs before transitioning to GLACIER

  ExpirationDays:
    Type: Number
    Default: 365
    Description: Number of days to retain logs before expiration

  WafWebAclArn:
    Type: String
    Default: ""
    Description: Name of the WAF Web ACL

  CreateSecurityTrail:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
    Description: Whether to create CloudTrail security trail

  CreateWafLogging:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
    Description: Whether to create WAF logging configuration

  CreateWafLoggingBucket:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
    Description: Whether to create WAF logging Bucket

  CreateSecurityTrailLoggingBucket:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
    Description: Whether to create Security Trail logging Bucket

Conditions:
  ShouldCreateSecurityTrail: !Equals [!Ref CreateSecurityTrail, 'true']
  ShouldCreateWafLogging: !Equals [!Ref CreateWafLogging, 'true']
  ShouldCreateWafLoggingBucket: !Equals [!Ref CreateWafLoggingBucket, 'true']
  ShouldCreateSecurityTrailBucket: !Equals [!Ref CreateSecurityTrailLoggingBucket, 'true']

Resources:
  WafLogsBucket:
    Type: AWS::S3::Bucket
    Condition: ShouldCreateWafLoggingBucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub 'aws-waf-logs-${AWS::AccountId}-${Environment}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToStandardIA
            Status: Enabled
            Transitions:
              - TransitionInDays: !Ref LogRetentionDays
                StorageClass: STANDARD_IA
          - Id: TransitionToGlacier
            Status: Enabled
            Transitions:
              - TransitionInDays: !Ref ArchiveRetentionDays
                StorageClass: GLACIER
          - Id: ExpireObjects
            Status: Enabled
            ExpirationInDays: !Ref ExpirationDays
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  CloudTrailLogsBucket:
    Type: AWS::S3::Bucket
    Condition: ShouldCreateSecurityTrailBucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub 'cloudtrail-logs-${AWS::AccountId}-${Environment}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToStandardIA
            Status: Enabled
            Transitions:
              - TransitionInDays: !Ref LogRetentionDays
                StorageClass: STANDARD_IA
          - Id: TransitionToGlacier
            Status: Enabled
            Transitions:
              - TransitionInDays: !Ref ArchiveRetentionDays
                StorageClass: GLACIER
          - Id: ExpireObjects
            Status: Enabled
            ExpirationInDays: !Ref ExpirationDays
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  WafLogsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: ShouldCreateWafLogging
    Properties:
      Bucket: !Ref WafLogsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AWSLogDeliveryWrite
            Effect: Allow
            Principal:
              Service: delivery.logs.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub '${WafLogsBucket.Arn}/*'
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
          - Sid: AWSLogDeliveryAclCheck
            Effect: Allow
            Principal:
              Service: delivery.logs.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !GetAtt WafLogsBucket.Arn

  CloudTrailLogsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: ShouldCreateSecurityTrail
    Properties:
      Bucket: !Ref CloudTrailLogsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AWSCloudTrailAclCheck
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !GetAtt CloudTrailLogsBucket.Arn
          - Sid: AWSCloudTrailWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub '${CloudTrailLogsBucket.Arn}/AWSLogs/*'
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control

  SecurityTrail:
    Type: AWS::CloudTrail::Trail
    Condition: ShouldCreateSecurityTrail
    DependsOn:
      - CloudTrailLogsBucketPolicy
    Properties:
      TrailName: SecurityTrail
      S3BucketName: !Ref CloudTrailLogsBucket
      IsLogging: true
      IsMultiRegionTrail: true
      IncludeGlobalServiceEvents: true
      EnableLogFileValidation: true

  WafLoggingConfiguration:
    Type: AWS::WAFv2::LoggingConfiguration
    Condition: ShouldCreateWafLogging
    Properties:
      ResourceArn: !Ref WafWebAclArn
      LogDestinationConfigs:
        - !GetAtt WafLogsBucket.Arn
      RedactedFields: []

Outputs:
  WafLogsBucketName:
    Condition: ShouldCreateWafLogging
    Description: Name of the WAF logs bucket
    Value: !Ref WafLogsBucket

  CloudTrailLogsBucketName:
    Condition: ShouldCreateSecurityTrail
    Description: Name of the CloudTrail logs bucket
    Value: !Ref CloudTrailLogsBucket
